import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ScrollbarSpacer } from "@/app/components/scrollbar-spacer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=LINE+Seed+JP:wght@400;500;600;700&display=swap"
        />
      </head>
      <body
        className={`bg-black font-sans antialiased ${
          process.env.NODE_ENV === "development" ? "debug-screens" : undefined
        }`}
      >
        <ScrollbarSpacer />
        {children}
      </body>
    </html>
  );
}
